dist: trusty
language: rust

rust: stable

env:
  global:
    - CRATE_NAME=cobalt
    # default job
    - TARGET=x86_64-unknown-linux-gnu

matrix:
  fast_finish: true
  include:
    # Linux
    # - env: TARGET=x86_64-unknown-linux-gnu  # this is the default job

    # OSX
    - env: TARGET=x86_64-apple-darwin
      os: osx

    # Testing other channels
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: beta
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly

install:
  - sh ci/install.sh
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh

before_deploy:
  - sh ci/before_deploy.sh

cache: cargo
before_cache:
    # Travis can't cache files that are not readable by "others"
    - chmod -R a+r $HOME/.cargo

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

# TODO: Upload coverage
#after_success:
 #- travis-cargo --only stable coveralls --no-sudo --exclude-pattern="src/main.rs,src/new.rs,target/debug/build/"

deploy:
  provider: releases
  api_key:
    secure: cvBmiUswjTLIKa5mehll8+6mEQPL91LfZu6DW97Al7GtFkf9evUTok/Z9C9YiyExNqcHoBpnC91nlHeev6tndd29VueP/HfGaQbCQeETDZ2MzNCPvonWse+LARYuSg+MTyx7vWvIed4zdY7ePdOEbuCiLcZJkjd+/NA+cX/K76Q=
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  on:
    condition: $TRAVIS_RUST_VERSION = stable
    tags: true
  skip_cleanup: true

#notifications:
  #webhooks:
    #urls:
      #- https://webhooks.gitter.im/e/7e08f15b115326957c31
    #on_success: change  # options: [always|never|change] default: always
    #on_failure: always  # options: [always|never|change] default: always
    #on_start: never     # options: [always|never|change] default: always
